title: Wilco doc
description: User documentation for the Wilco application
theme: just-the-docs

url: https://wilco-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
